#!/usr/bin/env bash
# Build the framework. Needs the .NET SDK (on PATH or in ~/.dotnet) and ONI_GAME set to the
# game's install folder.
set -euo pipefail
export PATH="$HOME/.dotnet:$PATH"
export DOTNET_CLI_TELEMETRY_OPTOUT=1
cd "$(dirname "$0")"

# THE VERSION STAMP, built the same way as the SimDLL's so the two components carry
# comparable identities. MAJOR.MINOR is hand-set in VERSION; the revision is this repo's commit
# count and the metadata is its short commit, so neither can drift from the history, and a
# dirty working tree gets a trailing `*` so a build made from uncommitted edits says so on the
# watermark. Everything degrades to a literal rather than failing -- a missing git must not be
# able to stop a build.
BASE=$(grep -v '^#' VERSION | tr -d '[:space:]')
REV=$(git rev-list --count HEAD 2>/dev/null || echo 0)
SHA=$(git rev-parse --short=7 HEAD 2>/dev/null || echo unknown)
DIRTY=""
[ -n "$(git status --porcelain 2>/dev/null)" ] && DIRTY="*"
VERSION="${BASE}.${REV}+${SHA}${DIRTY}"
echo "version: $VERSION"

# Generated, not tracked (.gitignore). Written every build so it can never be stale; the csproj
# refuses to compile without it rather than letting an unstamped assembly out.
cat > OniFramework/Version.generated.cs <<CS
// GENERATED BY build.sh -- DO NOT EDIT, DO NOT COMMIT. Rewritten on every build from the
// VERSION file and git. See OniFramework/BuildStamp.cs for what reads it.
namespace OniFramework
{
	internal static class GeneratedVersion
	{
		internal const string Value = "$VERSION";
	}
}
CS

# GUARD: THE FRAMEWORK MAY NOT CALL Debug.LogError.
#
# ONI's KCrashReporter treats LogType.Error exactly as it treats an unhandled exception: it
# pauses the sim with isCrashed:true, pops the "Oops-a-daisy" modal, walks the live stack and
# UNCHECKS every mod it finds there, and -- since terminateOnError defaults true and a player's
# install has no Dev-distribution mod to relax it -- offers no Continue button. For a shared
# library shipped alongside a replacement SimDLL that is not a loud log line, it is a crash the
# player attributes to us, raised for conditions this API already reports by return value.
#
# This is a check and not only a comment because a rule stated at one call site does not reach
# the others. Route everything through OniFramework.FrameworkLog instead; when a crash really is a crash, throw,
# because an exception carries its own stack and blames the mod actually at fault.
#
# Comment lines are exempt so the rule can be explained where it is enforced.
BAD=$(grep -rn 'Debug\.LogError' OniFramework/*.cs 2>/dev/null \
      | grep -vE ':[0-9]+:[[:space:]]*(//|\*|/\*)' || true)
if [ -n "$BAD" ]; then
  echo "build.sh: FAILED -- OniFramework may not call Debug.LogError:" >&2
  printf '%s\n' "$BAD" >&2
  echo "build.sh: use OniFramework.FrameworkLog.Error (warning level, ERROR in the text), or" >&2
  echo "build.sh: throw if it really is a crash. See OniFramework/FrameworkLog.cs." >&2
  exit 1
fi

dotnet build OniFramework/OniFramework.csproj -c Release --nologo -v minimal
echo "built OniFramework/bin/Release/OniFramework.dll  ($VERSION)"

# THE SDK SIMDLL, BUNDLED FOR SimDllDelivery. bin/Release is the mod folder (OniFramework.dll,
# mod.yaml, mod_info.yaml), and native/ inside it carries the library, its SHA-256, the game
# builds it supports and its version. A subfolder because the game's mod loader calls
# Assembly.LoadFrom on every *.dll at the top of a mod folder. native/ is rebuilt every time, so
# a framework built without a library never carries a stale one. The library comes from the sim
# repository beside this one (ONI_SIM_REPO overrides); build it first with its sim/build.sh.
OUT=OniFramework/bin/Release
rm -rf "$OUT/native"
SIM_REPO=${ONI_SIM_REPO:-}
if [ -z "$SIM_REPO" ] && [ -d ../oni-sim-replacement/sim ]; then
  SIM_REPO=../oni-sim-replacement
fi
if [ -n "$SIM_REPO" ] && [ -f "$SIM_REPO/sim/build/SimDLL.dll" ]; then
  [ -f "$SIM_REPO/installer/supported-builds.txt" ] || { echo "build.sh: $SIM_REPO/installer/supported-builds.txt is missing" >&2; exit 1; }
  mkdir -p "$OUT/native"
  cp "$SIM_REPO/sim/build/SimDLL.dll" "$OUT/native/SimDLL.dll"
  cp "$SIM_REPO/installer/supported-builds.txt" "$OUT/native/supported-builds.txt"
  sed -n '/^[^#[:space:]]/{p;q}' "$SIM_REPO/sim/VERSION" > "$OUT/native/VERSION"
  (cd "$OUT/native" && sha256sum SimDLL.dll > SHA256SUMS)
  echo "bundled $OUT/native/SimDLL.dll  ($(cat "$OUT/native/VERSION"), $(cut -c1-8 "$OUT/native/SHA256SUMS"))"
else
  echo "build.sh: no sim/build/SimDLL.dll found (set ONI_SIM_REPO), so the mod carries no SimDLL" >&2
fi
