using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using TemplateClasses;
using UnityEngine;

namespace OniFramework
{
	/// <summary>
	/// Writes a rig's own in-memory Klei template out as a <see cref="RigBlueprint"/> YAML file.
	///
	/// WHY THIS EXISTS RATHER THAN SOMEBODY TYPING THE YAML. The rigs still to be migrated onto the
	/// blueprint canvas do not have small scenarios. AirLoop assembles roughly forty buildings, a
	/// corridor of painted cells, two conduit networks, a wire run, five plants and its own vacuum
	/// jacket, all from interdependent local constants spread over 2800 lines. Hand-transcribing
	/// that into YAML is not a mechanical job -- it is forty chances to put a building one tile
	/// out, and every one of those lands as a physics failure in a rig whose whole subject is gas
	/// composition, where a misplaced diffuser and a broken mixer look identical in the verdict.
	///
	/// So the YAML is GENERATED FROM THE TEMPLATE THE RIG ACTUALLY BUILT. Whatever the C# produced
	/// is what the file contains, by construction, and the migration cannot introduce a geometry
	/// difference it would then have to debug as if it were a mechanism difference. Run once with
	/// the dump flag, keep the file, delete the builder.
	///
	/// It writes CANVAS coordinates, not template-local ones: a template's cells are relative to
	/// wherever it is stamped, and a blueprint's are absolute, so the origin the rig was going to
	/// stamp at is added here. That conversion is the one piece of arithmetic in this file and it
	/// is why the origin is a required argument rather than defaulted.
	///
	/// This is a DEVELOPMENT tool. Nothing calls it unless a rig is passed an explicit dump flag.
	/// </summary>
	public static class BlueprintDump
	{
		/// <summary>
		/// True when the process was launched with <c>--rig-dump-blueprint</c>. Rigs gate their
		/// dump call on this so a normal run never writes a file.
		/// </summary>
		public static bool Requested =>
			System.Array.IndexOf(System.Environment.GetCommandLineArgs(),
				"--rig-dump-blueprint") >= 0;

		/// <summary>
		/// Where a dump lands: beside the game's own log, which is the one directory every one of
		/// this project's tools already knows how to reach.
		/// </summary>
		public static string PathFor(string blueprintName)
		{
			return Path.Combine(Util.RootFolder(), blueprintName + ".dump.yaml");
		}

		/// <summary>
		/// Writes <paramref name="cells"/> and <paramref name="buildings"/> as a blueprint.
		/// Returns the path written, or null if nothing was.
		/// </summary>
		/// <param name="name">The blueprint's own name field.</param>
		/// <param name="originX">Canvas cell the template's local (0,0) lands on.</param>
		/// <param name="originY">See <paramref name="originX"/>.</param>
		/// <param name="canvasWidth">Canvas the generated file declares.</param>
		/// <param name="canvasHeight">See <paramref name="canvasWidth"/>.</param>
		/// <param name="regions">Named regions to emit, usually at least the rig's own block.</param>
		public static string Write(string name, IList<Cell> cells, IList<Prefab> buildings,
			int originX, int originY, int canvasWidth, int canvasHeight,
			IList<RegionSpec> regions)
		{
			var sb = new StringBuilder();
			CultureInfo c = CultureInfo.InvariantCulture;

			sb.AppendLine("# GENERATED by OniFramework.BlueprintDump from the rig's own template.");
			sb.AppendLine("# Every cell and building below is what the C# builder actually produced,");
			sb.AppendLine("# converted from template-local to canvas coordinates by adding the origin");
			sb.AppendLine("# the rig was going to stamp at. Edit freely once it is checked in -- but");
			sb.AppendLine("# regenerate rather than hand-patch if the builder is still around.");
			sb.AppendLine();
			sb.AppendLine("name: " + name);
			sb.AppendLine();
			sb.AppendLine("canvas:");
			sb.AppendLine("  width: " + canvasWidth.ToString(c));
			sb.AppendLine("  height: " + canvasHeight.ToString(c));
			sb.AppendLine("  background: Vacuum");
			sb.AppendLine("  backgroundTemperature: 293.15");
			sb.AppendLine("  border: Unobtanium");
			sb.AppendLine("  borderThickness: 1");
			sb.AppendLine("  zone: Sandstone");
			sb.AppendLine("  startX: " + Mathf.Clamp(originX + 2, 1, canvasWidth - 2).ToString(c));
			sb.AppendLine("  startY: " + Mathf.Clamp(originY + 2, 1, canvasHeight - 2).ToString(c));

			if (regions != null && regions.Count > 0)
			{
				sb.AppendLine();
				sb.AppendLine("regions:");
				foreach (RegionSpec r in regions)
				{
					sb.AppendLine("  - name: " + r.name);
					sb.AppendLine("    x: " + r.x.ToString(c));
					sb.AppendLine("    y: " + r.y.ToString(c));
					sb.AppendLine("    w: " + r.w.ToString(c));
					sb.AppendLine("    h: " + r.h.ToString(c));
				}
			}

			if (cells != null && cells.Count > 0)
			{
				sb.AppendLine();
				sb.AppendLine("cells:");
				foreach (Cell cell in cells)
				{
					if (cell == null)
					{
						continue;
					}
					sb.AppendLine("  - location_x: " + (cell.location_x + originX).ToString(c));
					sb.AppendLine("    location_y: " + (cell.location_y + originY).ToString(c));
					sb.AppendLine("    element: " + cell.element);
					sb.AppendLine("    mass: " + cell.mass.ToString("R", c));
					sb.AppendLine("    temperature: " + cell.temperature.ToString("R", c));
					if (cell.backwallElement != SimHashes.Vacuum && cell.backwallMass > 0f)
					{
						sb.AppendLine("    backwallElement: " + cell.backwallElement);
						sb.AppendLine("    backwallMass: " + cell.backwallMass.ToString("R", c));
						sb.AppendLine("    backwallTemperature: "
							+ cell.backwallTemperature.ToString("R", c));
					}
				}
			}

			if (buildings != null && buildings.Count > 0)
			{
				sb.AppendLine();
				sb.AppendLine("buildings:");
				foreach (Prefab p in buildings)
				{
					if (p == null)
					{
						continue;
					}
					sb.AppendLine("  - id: " + p.id);
					sb.AppendLine("    x: " + (p.location_x + originX).ToString(c));
					sb.AppendLine("    y: " + (p.location_y + originY).ToString(c));
					if (p.rotationOrientation != Orientation.Neutral)
					{
						sb.AppendLine("    orientation: " + p.rotationOrientation);
					}
					if (p.element != SimHashes.Void && p.element != (SimHashes)0)
					{
						sb.AppendLine("    element: " + p.element);
					}
					if (p.temperature > 0f)
					{
						sb.AppendLine("    temperature: " + p.temperature.ToString("R", c));
					}
					// ALWAYS EMITTED WHEN NON-ZERO, and this is the field that matters most in a
					// generated file. BlueprintBuilder.ComputeUtilityConnections bakes a mask from
					// blueprint-wide ADJACENCY and skips any spec that already has one -- so a run
					// the rig built as two separate networks would silently be joined into one on
					// reload if the masks were dropped here. PHASELOOP's own blueprint carries a
					// comment about exactly that, having had a cycle destroyed by it.
					if (p.connections != 0)
					{
						sb.AppendLine("    connections: " + p.connections.ToString(c));
					}
					if (p.storage != null && p.storage.Count > 0)
					{
						sb.AppendLine("    storage:");
						foreach (StorageItem item in p.storage)
						{
							if (item == null)
							{
								continue;
							}
							sb.AppendLine("      - id: " + item.id);
							sb.AppendLine("        units: " + item.units.ToString("R", c));
							if (item.temperature > 0f)
							{
								sb.AppendLine("        temperature: "
									+ item.temperature.ToString("R", c));
							}
						}
					}
				}
			}

			string path = PathFor(name);
			File.WriteAllText(path, sb.ToString());
			Debug.Log($"[OniFramework] BlueprintDump: wrote {cells?.Count ?? 0} cell(s) and "
				+ $"{buildings?.Count ?? 0} building(s) to {path}");
			return path;
		}
	}
}
